### ISSUE TITLE
[DOC] - Missing documentation on setting "Privileged Gateway Intents"

### ISSUE THREAD

**Issue by bradtaniguchi** [BeccaLyria/discord-documentation#564]
### What is incorrect in the documentation?

I don't believe the docs specify anything related to setting the "Privileged Gateway Intents" for a bot.
Which are documented here:
https://discord.com/developers/docs/topics/gateway#gateway-intents

I guess the bot requires the "Server Members Intent" to be active? This is a rather new feature to me so I'm honestly not 100% sure how it works, or why it was required, but toggling that feature on got me past the issues I ran into.

### What should that text say?

The docs should specify activating the following settings in the **bot** settings
![Screenshot 2021-10-04 19 21 44](https://user-images.githubusercontent.com/10079147/135950576-9f7db539-8fe8-4f3f-ba79-87d3baba36d2.png)
:

### Additional information

I dug into this, as I kept getting the following error when running the bot locally:
```
debug: 2021-10-05 02:20:23: Attaching event listeners...
debug: 2021-10-05 02:20:23: Connecting to Discord...
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/workspaces/discord-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:244:15)
    at async Client.login (/workspaces/discord-bot/node_modules/discord.js/src/client/Client.js:245:7)
```

The "googlable" part is the `DISALLOWED_INTENTS` portion, which led to the above linked cos.

**Comment by nhcarrigan** [comment]
Let's go ahead and add this to the `setup-code.md` file, just before the "Create a Webhook" section.

We should note that the `Server Member Intent` *must* be turned on, and that the `Public Bot` should be turned off if the contributor does not want others to be able to invite the bot to their servers.
